# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Repository Sync

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "langnang-temp/langnang.github.io"
          source_branch: "@langnang-temp/langnang.github.io"
          destination_branch: "@langnang-temp/langnang.github.io"
          github_token: ${{ secrets.GITHUB_TOKEN }}
